#!/bin/bash
#

USERNAME=yourusername
PASSWORD=yourpassword

if [ $# != 1 ]
then
	echo .Usage: tweet 'your message'
	exit 1
fi
curl --silent -u $USERNAME:$PASSWORD -d status="$1" http://twitter.com/statuses/update.xml >> /dev/null




